### ISSUE TITLE
404 on edit page after reload

### ISSUE THREAD

**Issue by andriivarhanov** [kalombos/react-crud-example#1]
![image](https://cloud.githubusercontent.com/assets/5204821/24224779/cba39c32-0f65-11e7-803d-e3953181e0ee.png)

http://take.ms/U9DzH

**Comment by kalombos** [comment]
@andriivarhanov thx for the report, i really like that somebody uses the project. [I have fixed the bug](https://github.com/kalombos/react-crud-example/commit/1b06f9902deb5280395249a9b2bad98ebe07157c#diff-509c8056f125848fd35e31bed9447bd1R30) and cleaned up a bit.

**Comment by andriivarhanov** [comment]
@kalombos thank you, looks great now. Actually I went to live demo because I couldn't set up backend locally. It would be great if you can take a look at the issue https://github.com/kalombos/react-crud-example/issues/2
