### ISSUE TITLE
Issues setup backend locally

### ISSUE THREAD

**Issue by andriivarhanov** [kalombos/react-crud-example#2]
Most likely I will be able to solve those issues after some time of back and forth with python and packages. But the reason why I creating the issue is to ask you consider Docker for local environment. With Docker I don't have to install dependencies to my system. 

Here is an example of python project what I could run locally successfully https://github.com/Seedstars/django-react-redux-base

Please consider using Docker for the project

![image](https://cloud.githubusercontent.com/assets/5204821/24239188/9941e8ac-0fb5-11e7-97ae-3a2cc058ca8f.png)

**Comment by kalombos** [comment]
I don't mind about Docker but, unfortunately, i have no experience with that tool. Therefore i will not give a promise to add docker in the project. But it is possible in some future. Anyway, you can always create a pull request with the feature.

**Comment by andriivarhanov** [comment]
@kalombos sure, I will

**Comment by andriivarhanov** [comment]
@kalombos sorry, docker pull request took a month. There is still some issues with db, can you please check this line https://github.com/kalombos/react-crud-example/pull/3/commits/646a49a6a37096cf7a67b21a54108c833c7030e5#diff-4e5e90c6228fd48698d074241c2ba760R20 and let me know what correct `DATABASE_URL` should be

**Comment by kalombos** [comment]
DATABASE_URL is needed for deployment the application in  Heroku CLOUD where i host it for the moment. I don't know how to setup Heroku for using docker you can [try to do it by yourself](https://devcenter.heroku.com/articles/container-registry-and-runtime), you can register a free account on heroku and deploy the application on the cloud. Or you can make docker optional for local development and leave application without docker for production. And please update README file with information how to deploy the application with docker.
